dist: focal
services:
  - docker
before_install:
  - docker pull tonysamperi/ts-luxon
  - docker build -t tonysamperi/ts-luxon -f ./docker/Dockerfile .
script:
  - docker build -t tonysamperi/ts-luxon -f ./docker/Dockerfile .
  - docker run --rm -v ${pwd}:/ts-luxon -w /tonysamperi/ts-luxon tonysamperi/ts-luxon npm install
