dist: focal
services:
  - docker
before_install:
  - docker pull tonysamperi/ts-luxon
  - apt-get update
  - apt-get install -y git
  - mkdir /home/ts-luxon
  - cd /home/ts-luxon
  - git clone https://github.com/tonysamperi/ts-luxon
script:
  - npm run build
  - npm run test
