dist: focal
services:
  - docker
before_install:
  - docker pull tonysamperi/ts-luxon
  - sudo ./docker/npm install
script:
  - sudo ./docker/npm run build
  - sudo ./docker/npm run lint
  - sudo ./docker/npm run test
  - sudo ./docker/npm run docs
  - sudo ./docker/npm run check-doc-coverage
  - bash <(curl -s https://codecov.io/bash)
