sudo: true
services:
 - docker
before_install:
  - docker pull tonysamperi/ts-luxon
  - docker run tonysamperi/ts-luxon /bin/sh -c "/tonysamperi/ts-luxon/docker/workflow.sh"
script:
 - /tonysamperi/ts-luxon/docker/workflow.sh